### ISSUE TITLE
你这和我的油猴脚本复制粘贴似的我就不说了，最重要的是我用的是 GPL-3.0 License，你却用的是 MIT License，这不对吧？...

### ISSUE THREAD

**Issue by XIU2** [Zenquan/githubHelper#3]
看了下截图和代码，跟复制粘贴似的... 
代码、变量、加速源及说明、HTML、SVG 图标，甚至注释都一样。 
不过这些都是开源协议所允许的，虽然有点别扭，但也没什么说的必要。

最重要的是我用的是 **GPL-3.0 License**，你却用的是 **MIT License**，这不对吧？...

https://github.com/XIU2/UserScript

**Comment by Zenquan** [comment]
不好意思，我的这个从v3版本开始确实很多是用的你的代码，开源协议的话我开始的时候没开清楚我是我的问题，我修改一下，实在抱歉。

**Comment by Zenquan** [comment]
后面把参考的代码去掉吧

**Comment by XIU2** [comment]
本来我只是想提醒你遵循开源协议将该项目 **MIT License** 改为 **GPL-3.0 License**，结果你这直接回退是我没想到的😅。。。
虽然有一些文件的代码你还没来得及改，不过主要是 `gh.xiu2.xyz` 这个加速源是我自建的，没有**授权**给其他任何项目使用欧~

**Comment by Zenquan** [comment]
gh.xiu2.xyz这个域名我这边会注意的哈
